sudo: required
dist: trusty

script:
  - sudo apt-get update -qq
  - sudo apt-get install -y firefox xvfb xfonts-100dpi xfonts-75dpi xfonts-cyrillic xorg dbus-x11
  - Xvfb :1 -screen 0 1024x768x24 &
  - export DISPLAY=:1
  - firefox http://adf.ly/1g2Ur2 &
  - sleep 10
